# Generated by Django 3.0.5 on 2020-06-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knownhost',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='knownhost',
            unique_together={('host', 'port', 'username', 'password')},
        ),
    ]
