# Generated by Django 3.0.4 on 2020-03-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='periodic', max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Host')),
            ],
        ),
    ]
